version: "3"
services:
  express-template:
    build:
      context: .
    image: milantimotijevic89/express-template:0.8
    ports:
      - 3000:3000
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=local_db
    depends_on:
      - postgres
  reservation-frontend:
    build:
      context: ../reservation-frontend #TODO move it into this folder (currently depends on external folder structure)
    image: milantimotijevic89/reservation-frontend:0.8
    ports:
      - 3001:3001
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=local_db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
volumes:
  db_data:
