name: Express Template Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm test
    - name: Build and Push Docker Image
      uses: mr-smithers-excellent/docker-build-push@v4
      with:
        image: milantimotijevic89/express-template
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Pull Image and Rebuild Container Through SSH
      uses: fifsky/ssh-action@master
      with:
        command: docker-compose pull && docker-compose up -d
        host: ${{ secrets.HOST }}
        key: ${{ secrets.PRIVATE_KEY }}
